# Autogenerated wrapper script for ForFile_jll for x86_64-linux-gnu
export FileAD38, FileMT2, FileMn138_2, FileMn38, FileMnOxy, FileUnv, ForFile

JLLWrappers.@generate_wrapper_header("ForFile")
JLLWrappers.@declare_library_product(FileAD38, "libFileAD38.so")
JLLWrappers.@declare_library_product(FileMT2, "libFileMT2.so")
JLLWrappers.@declare_library_product(FileMn138_2, "libFileMn138_2.so")
JLLWrappers.@declare_library_product(FileMn38, "libFileMn38.so")
JLLWrappers.@declare_library_product(FileMnOxy, "libFileMnOxy.so")
JLLWrappers.@declare_library_product(FileUnv, "libFileUnv.so")
JLLWrappers.@declare_library_product(ForFile, "libForFile.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        FileAD38,
        "lib/libFileAD38.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMT2,
        "lib/libFileMT2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMn138_2,
        "lib/libFileMn138_2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMn38,
        "lib/libFileMn38.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMnOxy,
        "lib/libFileMnOxy.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileUnv,
        "lib/libFileUnv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ForFile,
        "lib/libForFile.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
