# Autogenerated wrapper script for ForFile_jll for x86_64-w64-mingw32
export FileAD38, FileMT2, FileMn138_2, FileMn38, FileMnOxy, FileUnv, ForFile

JLLWrappers.@generate_wrapper_header("ForFile")
JLLWrappers.@declare_library_product(FileAD38, "libFileAD38.dll")
JLLWrappers.@declare_library_product(FileMT2, "libFileMT2.dll")
JLLWrappers.@declare_library_product(FileMn138_2, "libFileMn138_2.dll")
JLLWrappers.@declare_library_product(FileMn38, "libFileMn38.dll")
JLLWrappers.@declare_library_product(FileMnOxy, "libFileMnOxy.dll")
JLLWrappers.@declare_library_product(FileUnv, "libFileUnv.dll")
JLLWrappers.@declare_library_product(ForFile, "libForFile.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        FileAD38,
        "bin\\libFileAD38.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMT2,
        "bin\\libFileMT2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMn138_2,
        "bin\\libFileMn138_2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMn38,
        "bin\\libFileMn38.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileMnOxy,
        "bin\\libFileMnOxy.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FileUnv,
        "bin\\libFileUnv.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ForFile,
        "bin\\libForFile.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
